Repository Uot-Project3-Group05/uot-project3-group5, pull requests merged in 2021-05, with the labels that each got.

#13 front end main page
  client/package-lock.json
  client/package.json
  client/src/App.js
Labels: enhancement

#16 Feature/esroleo krispywing home profile components
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Game/index.js
  client/src/components/Home/index.js
  client/src/components/Nav/index.js
  client/src/components/Profile/index.js
Labels: enhancement

#17 Feature/esroleo krispywing home profile components
  client/src/components/Game/index.js
  client/src/components/Home/index.js
Labels: bug

#19 Feature/esroleo krispywing deck design
  client/src/components/Home/index.js
  client/src/components/Nav/index.js
  client/src/components/Profile/index.js
Labels: enhancement

#21 Feature/db models
  server/models/Deck.js
  server/models/User.js
  server/schemas/index.js
  server/schemas/typeDefs.js
Labels: enhancement

#22 esroleo-anagha-ali-login added email instead of username
  server/schemas/typeDefs.js
Labels: enhancement

#27 Feature/client side query mutation
  client/src/utils/queries.js
  server/models/Card.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#29 Feature/anagha ali esroleo get deck fe
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Home/index.js
  client/src/index.js
  client/src/utils/auth.js
  client/src/utils/queries.js
  server/package-lock.json
  server/package.json
Labels: enhancement

#30 Feature/shawn terrence ali logic
  client/package-lock.json
  client/package.json
  client/src/App.test.js
  client/src/__tests__/gameSession.test.js
  client/src/components/Game/index.js
  client/src/utils/gameLogic.js
  client/src/utils/helpers.js
  package-lock.json
  server/package-lock.json
Labels: enhancement

#32 Feature/ali anagha esrolo home fe
  client/package.json
  client/src/components/Game/index.js
  client/src/components/Home/index.js
  client/src/utils/queries.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#35 Feature/anagha esroleo game card styling
  client/src/assets/images/logoMD.png
  client/src/components/Game/index.js
  client/src/components/Home/index.js
  client/src/components/Nav/index.js
  client/src/components/Profile/index.js
Labels: enhancement

#36 Feature/krispywing signup login
  client/package-lock.json
  client/package.json
  client/src/components/Login/index.js
  client/src/components/Nav/index.js
  client/src/components/Signup/index.js
Labels: enhancement

#37 mvp completed
  client/src/assets/images/periodic-table.svg
  client/src/components/Home/index.js
  client/src/components/Login/index.js
  client/src/components/Nav/index.js
  client/src/components/Signup/index.js
Labels: enhancement

#38 Feature/ojashri ali pwa
  client/public/logoMD.png
  client/public/manifest.json
  client/src/components/Game/index.js
  client/src/components/Home/index.js
  client/src/utils/gameLogic.js
  client/src/utils/helpers.js
  client/src/utils/idb.js
Labels: enhancement

#40 use toast to show Authentication Error
  client/src/components/Home/index.js
Labels: enhancement

#43 Feature/signup login validation
  client/src/components/Login/index.js
  client/src/components/Signup/index.js
  package-lock.json
  server/package-lock.json
  server/schemas/resolvers.js
Labels: enhancement

#46 Feature/esroleo leaderboard static
  client/src/App.js
  client/src/components/Leaderboard/index.js
  client/src/components/Profile/index.js
Labels: enhancement

#48 Feature/shawn game modes
  client/src/__tests__/gameSession.test.js
  client/src/components/Game/index.js
  client/src/utils/gameLogic.js
Labels: enhancement

#50 Feature/team assemble game logic matrix changes
  client/src/components/Game/index.js
  client/src/utils/gameLogic.js
  server/models/Game.js
  server/models/User.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#52 tally results changes on front end
  client/src/components/Game/index.js
Labels: enhancement

#55 Feature/anagha esteban tally result
  client/src/components/Game/index.js
  client/src/components/Home/index.js
Labels: enhancement

#54 Bug/terrence shawn restart game
  client/src/components/Game/index.js
  client/src/utils/gameLogic.js
Labels: enhancement

#56 Feature/ali esteban model update
  client/package-lock.json
  client/src/utils/mutations.js
  client/src/utils/queries.js
  package-lock.json
  server/models/Game.js
  server/package-lock.json
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#58 implement addGame and getGame in front-end
  client/src/components/Game/index.js
  server/models/Game.js
Labels: enhancement

#59 updateGame mutation in fron-end
  client/src/components/Game/index.js
Labels: enhancement

#60 Feature/prevent default
  client/src/components/Game/index.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#57 Feature/johnny wu readme
  README.md
Labels: documentation

#61 Feature/ali esteban avatar
  client/src/components/Game/index.js
  client/src/components/Home/index.js
  client/src/components/Profile/index.js
  client/src/utils/queries.js
Labels: enhancement

#62 card mode text updated
  client/src/components/Game/index.js
Labels: enhancement

#64 positioning fixed for provile screen
  client/src/components/Profile/index.js
Labels: enhancement

#65 esroleo-ali-shawn fix game logic
  client/src/components/Signup/index.js
  server/seeders/data.js
Labels: bug

#66 Develop
  client/src/components/Profile/index.js
  client/src/components/Signup/index.js
  server/seeders/data.js
Labels: enhancement

#67 Feature/redirect to game profile
  client/src/App.js
  client/src/components/Profile/index.js
Labels: enhancement

#68 Develop
  client/src/App.js
  client/src/components/Profile/index.js
Labels: enhancement

#69 Feature/shawn add game end variable
  README.md
  client/src/utils/gameLogic.js
Labels: enhancement

#70 redirect-to home and images from profile
  client/src/components/Profile/index.js
Labels: enhancement

#72 Feature/length added profile image
  client/src/components/Profile/index.js
Labels: bug

#73 Develop
  README.md
  client/src/components/Profile/index.js
  client/src/utils/gameLogic.js
Labels: enhancement

#74 game-logic-fic
  client/src/components/Game/index.js
Labels: enhancement

#75 manifest.json, favicon, avatar
  client/public/favicon.ico
  client/public/manifest.json
  client/src/components/Nav/index.js
Labels: enhancement

#76 game starts automaticallya after finished now.
  client/src/components/Game/index.js
Labels: enhancement

#77 Develop
  client/public/favicon.ico
  client/public/manifest.json
  client/src/components/Game/index.js
  client/src/components/Nav/index.js
Labels: enhancement

#82 Feature/manifest update ali
  client/public/images/icons/icon-128x128.png
  client/public/images/icons/icon-144x144.png
  client/public/images/icons/icon-152x152.png
  client/public/images/icons/icon-192x192.png
  client/public/images/icons/icon-384x384.png
  client/public/images/icons/icon-512x512.png
  client/public/images/icons/icon-72x72.png
  client/public/images/icons/icon-96x96.png
  client/public/index.html
  client/public/manifest.json
Labels: enhancement

#83 manifest changes added
  client/public/manifest.json
Labels: enhancement

#85 Develop
  client/public/images/icons/icon-128x128.png
  client/public/images/icons/icon-144x144.png
  client/public/images/icons/icon-152x152.png
  client/public/images/icons/icon-192x192.png
  client/public/images/icons/icon-384x384.png
  client/public/images/icons/icon-512x512.png
  client/public/images/icons/icon-72x72.png
  client/public/images/icons/icon-96x96.png
  client/public/index.html
  client/public/manifest.json
Labels: enhancement
